import { Incident, IncidentCategory, RepairEvent, Hotspot } from '../../types';

export type ScenarioKey =
  | 'isolated'
  | 'recurring'
  | 'persistent'
  | 'duplicate'
  | 'resolved'
  | 'mixed_location';

export interface MemoryScenarioDefinition {
  key: ScenarioKey;
  label: string;
  badge: string;
  badgeColor: string;
  subtitle: string;
  description: string;
  primaryIncidentId: string;
  incidents: Incident[];
  repairs: RepairEvent[];
  hotspots: Hotspot[];
  expectedState: string;
  keyLearning: string;
}

export const MEMORY_SCENARIOS: Record<ScenarioKey, MemoryScenarioDefinition> = {
  isolated: {
    key: 'isolated',
    label: 'Isolated Incident',
    badge: 'NEW',
    badgeColor: 'bg-sky-50 text-sky-800 border-sky-200',
    subtitle: 'Sector 3 Malviya Nagar — Baseline coordinate with no prior records',
    description:
      'A fresh pothole reported today with zero historical complaints or municipal repairs within 350 meters.',
    primaryIncidentId: 'INC-ISO-01',
    expectedState: 'NEW',
    keyLearning:
      'CivicPulse recognizes this as a baseline incident. No false recurrence alerts or duplicate warnings are triggered.',
    incidents: [
      {
        id: 'INC-ISO-01',
        title: 'Fresh Pothole Formation near Market Gate',
        description: 'New road cavity forming after evening supply truck traffic. Edge crumbling visible near stormwater curb.',
        category: 'Pothole',
        severity: 'medium',
        status: 'active',
        address: 'Near Central Spine Market, Sector 3, Malviya Nagar',
        zone: 'South Zone',
        latitude: 26.8520,
        longitude: 75.8210,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        source: 'Citizen Report',
        tags: ['bitumen', 'market-entry', 'curb-damage'],
        imageUrl: null,
        aiAnalysis: null,
        recurrenceCount: 0,
        relatedIncidentIds: [],
        repairEventIds: [],
      },
    ],
    repairs: [],
    hotspots: [],
  },

  recurring: {
    key: 'recurring',
    label: 'Recurring Failure (2-Cycle)',
    badge: 'RECURRING',
    badgeColor: 'bg-purple-50 text-purple-800 border-purple-200',
    subtitle: 'Tonk Road Elevated Flyover — Defect reappeared after prior patch repair',
    description:
      'Incident INC-REC-02 was reported 37 days after repair work order REP-REC-01 was executed at the same spot.',
    primaryIncidentId: 'INC-REC-02',
    expectedState: 'RECURRING',
    keyLearning:
      'CivicPulse links the new incident to the historical record and repair event, highlighting the 37-day interval without claiming causality.',
    incidents: [
      {
        id: 'INC-REC-01',
        title: 'Crater Under Pillar 14 Tonk Flyover',
        description: 'Severe cavity in fast lane directly beneath flyover expansion joint drainage spout.',
        category: 'Pothole',
        severity: 'high',
        status: 'resolved',
        address: 'Pillar 14, Under Tonk Road Elevated Flyover',
        zone: 'Central-South Corridor',
        latitude: 26.8795,
        longitude: 75.8015,
        createdAt: '2026-07-10T09:30:00.000Z',
        updatedAt: '2026-07-14T17:00:00.000Z',
        source: 'Citizen Report',
        tags: ['tonk-road', 'pillar-14', 'flyover'],
        imageUrl: null,
        aiAnalysis: null,
        recurrenceCount: 0,
        relatedIncidentIds: ['INC-REC-02'],
        repairEventIds: ['REP-REC-01'],
      },
      {
        id: 'INC-REC-02',
        title: 'Bitumen Degradation & Cavity at Pillar 14',
        description: 'Surface layer delaminating at the exact previous patch location. Aggregate stones scattered into carriageway.',
        category: 'Pothole',
        severity: 'high',
        status: 'active',
        address: 'Pillar 14, Under Tonk Road Elevated Flyover',
        zone: 'Central-South Corridor',
        latitude: 26.8796,
        longitude: 75.8016,
        createdAt: '2026-08-16T11:15:00.000Z',
        updatedAt: '2026-08-16T11:15:00.000Z',
        source: 'Operator Entry',
        tags: ['tonk-road', 'pillar-14', 'recurrence'],
        imageUrl: null,
        aiAnalysis: null,
        recurrenceCount: 1,
        relatedIncidentIds: ['INC-REC-01'],
        repairEventIds: ['REP-REC-01'],
      },
    ],
    repairs: [
      {
        id: 'REP-REC-01',
        incidentId: 'INC-REC-01',
        date: '2026-07-13T14:00:00.000Z',
        action: 'Rapid Cold-Mix Bitumen Infill & Compaction',
        contractorOrTeam: 'Shree Balaji Infrastructure Pvt Ltd',
        costEstimate: '₹24,500',
        description: 'Temporary cold bituminous mix placed and hand-tamped during monsoon emergency window.',
        source: 'Municipal Work Order Registry',
        createdAt: '2026-07-13T14:00:00.000Z',
      },
    ],
    hotspots: [],
  },

  persistent: {
    key: 'persistent',
    label: 'Persistent Infrastructure Defect',
    badge: 'PERSISTENT',
    badgeColor: 'bg-rose-50 text-rose-800 border-rose-200',
    subtitle: 'Tonk Road Elevated Corridor — 4 failure cycles, 3 repairs, short ~30d intervals',
    description:
      'A chronic structural failure node. 4 incidents and 3 separate work orders cataloged over 94 days with active unclosed ticket.',
    primaryIncidentId: 'INC-PER-04',
    expectedState: 'PERSISTENT',
    keyLearning:
      'CivicPulse identifies chronic systemic fatigue. The Failure Fingerprint calculates a high Pattern Index (84/100) and displays complete repair cycle breakdowns.',
    incidents: [
      {
        id: 'INC-PER-01',
        title: 'Initial Carriageway Pothole near Pillar 14',
        description: 'Deep pavement crater forming beneath flyover joint.',
        category: 'Pothole',
        severity: 'high',
        status: 'resolved',
        address: 'Pillar 14, Under Tonk Road Elevated Flyover',
        zone: 'Central-South Corridor',
        latitude: 26.8795,
        longitude: 75.8015,
        createdAt: '2026-06-10T08:00:00.000Z',
        updatedAt: '2026-06-14T18:00:00.000Z',
        source: 'Citizen Report',
        tags: ['tonk-road', 'pillar-14'],
        imageUrl: null,
        aiAnalysis: null,
        recurrenceCount: 0,
        relatedIncidentIds: ['INC-PER-02', 'INC-PER-03', 'INC-PER-04'],
        repairEventIds: ['REP-PER-01'],
      },
      {
        id: 'INC-PER-02',
        title: 'Re-opened Cavity Following Heavy Rains',
        description: 'Bitumen patch loosened after monsoon precipitation.',
        category: 'Pothole',
        severity: 'high',
        status: 'resolved',
        address: 'Pillar 14, Under Tonk Road Elevated Flyover',
        zone: 'Central-South Corridor',
        latitude: 26.8796,
        longitude: 75.8014,
        createdAt: '2026-07-18T10:30:00.000Z',
        updatedAt: '2026-07-22T16:00:00.000Z',
        source: 'Operator Entry',
        tags: ['tonk-road', 'pillar-14', 'water-damage'],
        imageUrl: null,
        aiAnalysis: null,
        recurrenceCount: 1,
        relatedIncidentIds: ['INC-PER-01', 'INC-PER-03', 'INC-PER-04'],
        repairEventIds: ['REP-PER-01', 'REP-PER-02'],
      },
      {
        id: 'INC-PER-03',
        title: 'Structural Subsurface Crumbling at Pillar 14',
        description: 'Crater widened to 1.8 meters across both driving lanes.',
        category: 'Pothole',
        severity: 'critical',
        status: 'resolved',
        address: 'Pillar 14, Under Tonk Road Elevated Flyover',
        zone: 'Central-South Corridor',
        latitude: 26.8795,
        longitude: 75.8015,
        createdAt: '2026-08-14T14:15:00.000Z',
        updatedAt: '2026-08-18T19:00:00.000Z',
        source: 'Sensor Network',
        tags: ['tonk-road', 'traffic-hazard', 'pillar-14'],
        imageUrl: null,
        aiAnalysis: null,
        recurrenceCount: 2,
        relatedIncidentIds: ['INC-PER-01', 'INC-PER-02', 'INC-PER-04'],
        repairEventIds: ['REP-PER-02', 'REP-PER-03'],
      },
      {
        id: 'INC-PER-04',
        title: 'Subsurface Pothole & Water Regurgitation Re-emerged',
        description: 'Third patch failed. Water ponding observed bubbling from sub-base layer under traffic vibration.',
        category: 'Pothole',
        severity: 'critical',
        status: 'active',
        address: 'Pillar 14, Under Tonk Road Elevated Flyover',
        zone: 'Central-South Corridor',
        latitude: 26.8795,
        longitude: 75.8016,
        createdAt: '2026-09-12T07:45:00.000Z',
        updatedAt: '2026-09-12T07:45:00.000Z',
        source: 'Citizen Report',
        tags: ['tonk-road', 'critical', 'chronic-failure'],
        imageUrl: null,
        aiAnalysis: null,
        recurrenceCount: 3,
        relatedIncidentIds: ['INC-PER-01', 'INC-PER-02', 'INC-PER-03'],
        repairEventIds: ['REP-PER-01', 'REP-PER-02', 'REP-PER-03'],
      },
    ],
    repairs: [
      {
        id: 'REP-PER-01',
        incidentId: 'INC-PER-01',
        date: '2026-06-13T15:00:00.000Z',
        action: 'Cold Emulsion Bituminous Patching',
        contractorOrTeam: 'Shree Balaji Infrastructure Pvt Ltd',
        costEstimate: '₹22,000',
        description: 'Tack coat applied, 40mm asphalt concrete hand-compacted.',
        source: 'Work Order #4829',
        createdAt: '2026-06-13T15:00:00.000Z',
      },
      {
        id: 'REP-PER-02',
        incidentId: 'INC-PER-02',
        date: '2026-07-21T11:30:00.000Z',
        action: 'WBM Sub-base Reinforcement & Asphalt Overlay',
        contractorOrTeam: 'Jaipur Zonal Road Works Div 3',
        costEstimate: '₹42,500',
        description: 'Aggregate stone base leveled and dense bituminous macadam laid.',
        source: 'Work Order #5190',
        createdAt: '2026-07-21T11:30:00.000Z',
      },
      {
        id: 'REP-PER-03',
        incidentId: 'INC-PER-03',
        date: '2026-08-17T16:45:00.000Z',
        action: 'Rapid Setting Polymer Modified Concrete Infill',
        contractorOrTeam: 'Apex Urban Tech Contractors',
        costEstimate: '₹68,000',
        description: 'Rapid setting high-strength mortar placed with edge sealant.',
        source: 'Work Order #5633',
        createdAt: '2026-08-17T16:45:00.000Z',
      },
    ],
    hotspots: [
      {
        id: 'HOT-PER-01',
        locationName: 'Tonk Road Flyover Corridor (Pillar 14)',
        address: 'Pillar 14, Tonk Road Flyover',
        zone: 'Central-South Corridor',
        latitude: 26.8795,
        longitude: 75.8015,
        dominantCategory: 'Pothole',
        incidentCount: 4,
        activeCount: 1,
        repairCount: 3,
        mostRecentIncidentDate: '2026-09-12T07:45:00.000Z',
        recurrenceState: 'PERSISTENT',
        avgIntervalDays: 31,
        linkedIncidentIds: ['INC-PER-01', 'INC-PER-02', 'INC-PER-03', 'INC-PER-04'],
        riskScore: 88,
      },
    ],
  },

  duplicate: {
    key: 'duplicate',
    label: 'Potential Duplicate Report',
    badge: 'DUPLICATE DETECTED',
    badgeColor: 'bg-amber-50 text-amber-800 border-amber-200',
    subtitle: 'JLN Marg near Commerce College — 42m away from active unclosed ticket',
    description:
      'Two citizens reported the same defect 42 meters and 2 days apart while the initial complaint is still under investigation.',
    primaryIncidentId: 'INC-DUP-02',
    expectedState: 'NEW',
    keyLearning:
      'CivicPulse distinguishes LIKELY_DUPLICATE from RECURRING_FAILURE. It presents a prominent warning, offers "View Existing Ticket" or "Report as New".',
    incidents: [
      {
        id: 'INC-DUP-01',
        title: 'Large Crater in Middle Carriage Lane JLN Marg',
        description: 'Vehicles forced to brake abruptly during peak traffic hours near University Commerce College.',
        category: 'Pothole',
        severity: 'high',
        status: 'investigating',
        address: 'Opposite University Commerce College, JLN Marg',
        zone: 'East Zone',
        latitude: 26.8845,
        longitude: 75.8118,
        createdAt: '2026-09-16T14:20:00.000Z',
        updatedAt: '2026-09-17T09:00:00.000Z',
        source: 'Citizen Report',
        tags: ['jln-marg', 'traffic-hazard', 'lane-2'],
        imageUrl: null,
        aiAnalysis: null,
        recurrenceCount: 0,
        relatedIncidentIds: ['INC-DUP-02'],
        repairEventIds: [],
      },
      {
        id: 'INC-DUP-02',
        title: 'Dangerous Road Hole opposite Commerce College',
        description: 'Deep road cavity causing severe evening traffic bottleneck on JLN Marg near pedestrian zebra crossing.',
        category: 'Pothole',
        severity: 'high',
        status: 'active',
        address: 'Opposite University Commerce College, JLN Marg',
        zone: 'East Zone',
        latitude: 26.8848,
        longitude: 75.8120,
        createdAt: '2026-09-18T16:40:00.000Z',
        updatedAt: '2026-09-18T16:40:00.000Z',
        source: 'Citizen Report',
        tags: ['jln-marg', 'pedestrian-crossing'],
        imageUrl: null,
        aiAnalysis: null,
        recurrenceCount: 0,
        relatedIncidentIds: ['INC-DUP-01'],
        repairEventIds: [],
      },
    ],
    repairs: [],
    hotspots: [],
  },

  resolved: {
    key: 'resolved',
    label: 'Resolved Historical Failure',
    badge: 'RESOLVED',
    badgeColor: 'bg-emerald-50 text-emerald-800 border-emerald-200',
    subtitle: 'Main Boulevard, C-Scheme — Reinforced concrete overlay, no defect for 90+ days',
    description:
      'A location with two historical failures where comprehensive engineering reconstruction was completed. Zero active tickets open.',
    primaryIncidentId: 'INC-RES-02',
    expectedState: 'RESOLVED',
    keyLearning:
      'CivicPulse displays historical remediation success. Shows completed work orders and confirms operational stability.',
    incidents: [
      {
        id: 'INC-RES-01',
        title: 'Pavement Failure along Ashok Nagar Boulevard',
        description: 'Extensive alligator cracking and asphalt rutting near commercial bank arcade.',
        category: 'Pothole',
        severity: 'medium',
        status: 'resolved',
        address: 'Main Boulevard, C-Scheme Ashok Nagar',
        zone: 'Central Zone',
        latitude: 26.9080,
        longitude: 75.8020,
        createdAt: '2026-05-10T11:00:00.000Z',
        updatedAt: '2026-05-16T18:00:00.000Z',
        source: 'Citizen Report',
        tags: ['c-scheme', 'commercial-zone'],
        imageUrl: null,
        aiAnalysis: null,
        recurrenceCount: 0,
        relatedIncidentIds: ['INC-RES-02'],
        repairEventIds: ['REP-RES-01'],
      },
      {
        id: 'INC-RES-02',
        title: 'Surface Cratering Re-emerged near Bank Arcade',
        description: 'Cracking extended into pedestrian crossing boundary.',
        category: 'Pothole',
        severity: 'high',
        status: 'resolved',
        address: 'Main Boulevard, C-Scheme Ashok Nagar',
        zone: 'Central Zone',
        latitude: 26.9082,
        longitude: 75.8022,
        createdAt: '2026-06-14T09:30:00.000Z',
        updatedAt: '2026-06-22T17:00:00.000Z',
        source: 'Operator Entry',
        tags: ['c-scheme', 'engineering-review'],
        imageUrl: null,
        aiAnalysis: null,
        recurrenceCount: 1,
        relatedIncidentIds: ['INC-RES-01'],
        repairEventIds: ['REP-RES-01', 'REP-RES-02'],
      },
    ],
    repairs: [
      {
        id: 'REP-RES-01',
        incidentId: 'INC-RES-01',
        date: '2026-05-15T14:00:00.000Z',
        action: 'Bituminous Tack Coat & Surface Overlay',
        contractorOrTeam: 'Marwar Road Builders',
        costEstimate: '₹28,000',
        description: 'Surface patching across 15 sq meters.',
        source: 'Work Order #3911',
        createdAt: '2026-05-15T14:00:00.000Z',
      },
      {
        id: 'REP-RES-02',
        incidentId: 'INC-RES-02',
        date: '2026-06-20T10:00:00.000Z',
        action: 'M-40 Grade Reinforced Rigid Concrete White-Topping',
        contractorOrTeam: 'Jaipur Smart City Infrastructure Wing',
        costEstimate: '₹1,24,000',
        description: 'Complete milled sub-base excavation, dowel bar placement, and 150mm rigid concrete slab white-topping.',
        source: 'Work Order #4104',
        createdAt: '2026-06-20T10:00:00.000Z',
      },
    ],
    hotspots: [],
  },

  mixed_location: {
    key: 'mixed_location',
    label: 'Mixed-Category Location Memory',
    badge: 'CATEGORY SEGREGATED',
    badgeColor: 'bg-indigo-50 text-indigo-800 border-indigo-200',
    subtitle: 'Maharani Farm Junction — Pothole (3), Streetlight (2), Drainage (1) at same node',
    description:
      'Demonstrates category context preservation. CivicPulse tracks failure lineages separately for Potholes vs Streetlights vs Drainage even at the exact same road junction.',
    primaryIncidentId: 'INC-MIX-P3',
    expectedState: 'PERSISTENT',
    keyLearning:
      'A pothole complaint does not merge with a streetlight complaint into a single failure just because they are on the same street. Category context is strictly segregated.',
    incidents: [
      // Pothole Lineage (3 incidents, 1 repair) -> PERSISTENT
      {
        id: 'INC-MIX-P1',
        title: 'Asphalt Pothole at Maharani Farm Turning',
        description: 'Surface rutting near bus stop bay.',
        category: 'Pothole',
        severity: 'medium',
        status: 'resolved',
        address: 'Maharani Farm Junction, Durgapura',
        zone: 'South Zone',
        latitude: 26.8530,
        longitude: 75.7790,
        createdAt: '2026-07-05T08:00:00.000Z',
        updatedAt: '2026-07-08T16:00:00.000Z',
        source: 'Citizen Report',
        tags: ['junction', 'bus-stop'],
        imageUrl: null,
        aiAnalysis: null,
        recurrenceCount: 0,
        relatedIncidentIds: ['INC-MIX-P2', 'INC-MIX-P3'],
        repairEventIds: ['REP-MIX-P1'],
      },
      {
        id: 'INC-MIX-P2',
        title: 'Deep Cavity Re-emerged at Bus Stop Bay',
        description: 'Cold patch washed out by heavy monsoon runoff.',
        category: 'Pothole',
        severity: 'high',
        status: 'resolved',
        address: 'Maharani Farm Junction, Durgapura',
        zone: 'South Zone',
        latitude: 26.8531,
        longitude: 75.7791,
        createdAt: '2026-08-12T10:30:00.000Z',
        updatedAt: '2026-08-15T18:00:00.000Z',
        source: 'Citizen Report',
        tags: ['bus-stop', 'water-ponding'],
        imageUrl: null,
        aiAnalysis: null,
        recurrenceCount: 1,
        relatedIncidentIds: ['INC-MIX-P1', 'INC-MIX-P3'],
        repairEventIds: ['REP-MIX-P1'],
      },
      {
        id: 'INC-MIX-P3',
        title: 'Severe Structural Crater in Left Turn Lane',
        description: 'Vehicles bottoming out when navigating turn towards Gopalpura bypass.',
        category: 'Pothole',
        severity: 'critical',
        status: 'active',
        address: 'Maharani Farm Junction, Durgapura',
        zone: 'South Zone',
        latitude: 26.8530,
        longitude: 75.7792,
        createdAt: '2026-09-10T09:00:00.000Z',
        updatedAt: '2026-09-10T09:00:00.000Z',
        source: 'Citizen Report',
        tags: ['left-turn', 'gopalpura-bypass'],
        imageUrl: null,
        aiAnalysis: null,
        recurrenceCount: 2,
        relatedIncidentIds: ['INC-MIX-P1', 'INC-MIX-P2'],
        repairEventIds: ['REP-MIX-P1'],
      },

      // Streetlight Lineage (2 incidents) -> RECURRING
      {
        id: 'INC-MIX-S1',
        title: 'Twin High-Mast Luminaire Blackout',
        description: 'Junction lighting fixture unlit due to junction box short.',
        category: 'Broken Streetlight',
        severity: 'medium',
        status: 'resolved',
        address: 'Maharani Farm Junction, Durgapura',
        zone: 'South Zone',
        latitude: 26.8533,
        longitude: 75.7790,
        createdAt: '2026-08-01T20:00:00.000Z',
        updatedAt: '2026-08-04T12:00:00.000Z',
        source: 'Sensor Network',
        tags: ['electrical', 'high-mast'],
        imageUrl: null,
        aiAnalysis: null,
        recurrenceCount: 0,
        relatedIncidentIds: ['INC-MIX-S2'],
        repairEventIds: ['REP-MIX-S1'],
      },
      {
        id: 'INC-MIX-S2',
        title: 'Intermittent Light Flickering & Tripping',
        description: 'High mast fixture cuts out every 15 minutes during evening traffic.',
        category: 'Broken Streetlight',
        severity: 'medium',
        status: 'active',
        address: 'Maharani Farm Junction, Durgapura',
        zone: 'South Zone',
        latitude: 26.8534,
        longitude: 75.7789,
        createdAt: '2026-09-05T19:30:00.000Z',
        updatedAt: '2026-09-05T19:30:00.000Z',
        source: 'Citizen Report',
        tags: ['electrical', 'flicker'],
        imageUrl: null,
        aiAnalysis: null,
        recurrenceCount: 1,
        relatedIncidentIds: ['INC-MIX-S1'],
        repairEventIds: ['REP-MIX-S1'],
      },

      // Drainage Issue (1 incident) -> NEW
      {
        id: 'INC-MIX-D1',
        title: 'Stormwater Catch Pit Choked with Silt',
        description: 'Curb inlet blocked by construction debris from adjacent retail building.',
        category: 'Drainage Issue',
        severity: 'low',
        status: 'active',
        address: 'Maharani Farm Junction, Durgapura',
        zone: 'South Zone',
        latitude: 26.8529,
        longitude: 75.7794,
        createdAt: '2026-09-01T15:00:00.000Z',
        updatedAt: '2026-09-01T15:00:00.000Z',
        source: 'Operator Entry',
        tags: ['drainage', 'silt'],
        imageUrl: null,
        aiAnalysis: null,
        recurrenceCount: 0,
        relatedIncidentIds: [],
        repairEventIds: [],
      },
    ],
    repairs: [
      {
        id: 'REP-MIX-P1',
        incidentId: 'INC-MIX-P1',
        date: '2026-07-07T14:00:00.000Z',
        action: 'Cold Emulsion Bituminous Pothole Infill',
        contractorOrTeam: 'South Zone PWD Maintenance Wing',
        costEstimate: '₹18,500',
        description: 'Emergency patch infill.',
        source: 'Work Order #4501',
        createdAt: '2026-07-07T14:00:00.000Z',
      },
      {
        id: 'REP-MIX-S1',
        incidentId: 'INC-MIX-S1',
        date: '2026-08-03T11:00:00.000Z',
        action: 'Substation MCB Breaker Replacement & Cable Jointing',
        contractorOrTeam: 'Jaipur Discom Electrical Maintenance',
        costEstimate: '₹8,200',
        description: 'Replaced charred 63A breaker in roadside distribution box.',
        source: 'Work Order #4722',
        createdAt: '2026-08-03T11:00:00.000Z',
      },
    ],
    hotspots: [],
  },
};
